# .github/workflows/pages.yml
name: Deploy static content to Pages

on:
  push:
    branches: ["master"]          # change to "main" if that’s your default
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ↘ Build -------------------------------------------------------------
      - uses: actions/setup-node@v4
        with:
          node-version: 20           # current LTS
          cache: npm                 # speed up installs

      - run: npm ci                  # deterministic install

      - name: Build site
        run: |
          CI=false npm run build
        env:
          VITE_SUPABASE_URL:  ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # ↘ Publish -----------------------------------------------------------
      - uses: actions/configure-pages@v4

      # Upload build output as artifact for deployment
      - uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist                 # <- vite’s default output

      - id: deploy
        uses: actions/deploy-pages@v4
